/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-script-component-in-head */
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();
  const [sourcex, setSourcex] = useState([]);
  const [loading, setLoading] = useState(true);


  useEffect(() => {
    fetchData();
  }, []);


  const fetchData = async (next = null) => {
    try {

      const currentUrl = window.location.href;
      // Parse the URL to get the domain.
      const url = new URL(currentUrl);
  
      const domain = url.hostname;
      
      let res = await fetch(`https://${domain}/api/links/`, {
        method: "POST",
        body: JSON.stringify(
          { next: next }
        )
      })
      let datax = await res.json();
      if (res.status === 200 && datax.err == false) {
        setSourcex(datax.data);
      }
    } catch (e) {
      console.log("Error: ", e);
    } finally {
      setLoading(false);
    }
  }


  return (
    <>
      <Head>
        <title>Streaming App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div style={{ width: "100vw", height: "100vh" }} id="container" >
        {loading == true ? <div>Loading....</div> :
          <div style={{ width: "100%", height: "100%", padding: "20px" }} >
            {sourcex.map((e) => {
              return (<div key={e.id} style={{ cursor: "pointer", border: "1px solid black", marginTop: "10px", marginBottom: "10px" }} onClick={() => {
                router.push({
                  pathname: "player/", query: {
                    "id": e.src,
                    "type": e.type
                  }
                });
              }}>
                <img src={e.img} alt='' style={{ width: "100%", height: "150px" }}></img>
                <p>{e.title}</p>
              </div>);
            })}
          </div>}

        {/* <Image src={e.img} width={100} height={100} alt=''></Image>   <iframe class="metaframe rptss" style={{ width: "100%", height: "100%" }} src="http://bdix.live/wc23.html" frameborder="0" scrolling="no" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        <iframe class="metaframe rptss" style={{ width: "100%", height: "100%" }} src="http://bdix.live/gtv.html" frameborder="0" scrolling="no" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        <iframe class="metaframe rptss" style={{ width: "100%", height: "100%" }} src="http://bdix.live/10sp.html" frameborder="0" scrolling="no" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        <iframe allowfullscreen="" style={{ width: "100%", height: "100%" }} src="http://15.1.5.14:8082/2LIVE/embed.html?token=28154166b9b0db44ae0b446290015e99c7e0e07d-ea38795a20b053ef3b609d67f5837bd4-1696870259-1696859459&amp;remote=no_check_ip"></iframe>
        <iframe allowfullscreen="" style={{ width: "100%", height: "100%" }} src="http://15.1.5.10:8082/1LIVE/embed.html?token=a6bce7215cd3741669de536ea98ebd32b10d510a-a8aa245e64f1e989aa8d2284f69142b4-1696869658-1696858858&amp;remote=no_check_ip"></iframe>*/}
      </div>
    </>
  )
}
